name: Build OCR Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Create Version File
        # Needed because the project expects a GitVersion.cs file that isn't in the repo
        run: |
          echo 'using System.Reflection; [assembly: AssemblyVersion("1.0.0.0")] [assembly: AssemblyFileVersion("1.0.0.0")] [assembly: AssemblyInformationalVersion("1.0.0.0")]' > GitVersion.cs

      - name: Restore Packages
        run: msbuild -t:restore "QuickLook.Plugin/QuickLook.Plugin.ImageViewerOCR/QuickLook.Plugin.ImageViewer.csproj"

      - name: Build
        run: msbuild "QuickLook.Plugin/QuickLook.Plugin.ImageViewerOCR/QuickLook.Plugin.ImageViewer.csproj" /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: OCR-Plugin
          path: QuickLook.Plugin/QuickLook.Plugin.ImageViewerOCR/bin/Release/
