name: Build OCR Plugin Custom
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Create Missing Version File
        run: |
          echo 'using System.Reflection; [assembly: AssemblyVersion("1.0.0.0")] [assembly: AssemblyFileVersion("1.0.0.0")] [assembly: AssemblyInformationalVersion("1.0.0.0")]' > GitVersion.cs

      - name: Restore OCR Plugin
        run: msbuild -t:restore "QuickLook.Plugin/QuickLook.Plugin.ImageViewerOCR/QuickLook.Plugin.ImageViewer.csproj"

      - name: Build OCR Plugin
        # We add /p:BuildProjectReferences=false to stop it from pulling in the conflicting HtmlViewer
        run: msbuild "QuickLook.Plugin/QuickLook.Plugin.ImageViewerOCR/QuickLook.Plugin.ImageViewer.csproj" /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackages=false /p:PreBuildEvent= /p:AutoGenerateBindingRedirects=true /p:BuildProjectReferences=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OCR-Plugin-DLL
          path: QuickLook.Plugin/QuickLook.Plugin.ImageViewerOCR/bin/Release/
